const { test, expect } = require("@playwright/test");

function uniqueLabel(prefix) {
  return `${prefix} ${Date.now()} ${Math.floor(Math.random() * 1000)}`;
}

function futureLocalDatetime(daysAhead = 14, hour = 18, minute = 0) {
  const value = new Date();
  value.setDate(value.getDate() + daysAhead);
  value.setHours(hour, minute, 0, 0);
  const year = value.getFullYear();
  const month = String(value.getMonth() + 1).padStart(2, "0");
  const day = String(value.getDate()).padStart(2, "0");
  const hours = String(value.getHours()).padStart(2, "0");
  const minutes = String(value.getMinutes()).padStart(2, "0");
  return `${year}-${month}-${day}T${hours}:${minutes}`;
}

async function login(page, email, password) {
  await page.goto("/");
  await page.getByTestId("login-email").fill(email);
  await page.getByTestId("login-password").fill(password);
  await page.getByTestId("login-submit").click();
}

async function loginAsStudent(page) {
  await login(page, "student@example.com", "Student123!");
  await expect(page).toHaveURL(/\/dashboard$/);
}

async function loginAsAdmin(page) {
  await login(page, "admin@example.com", "Admin123!");
  await expect(page).toHaveURL(/\/dashboard$/);
}

function getEventCard(page, title) {
  return page.locator("#event-match-list .event-match-card").filter({ hasText: title }).first();
}

async function openNotificationMenu(page) {
  await expect(page.getByTestId("notification-trigger")).toBeVisible();
  await page.getByTestId("notification-trigger").click();
  await expect(page.getByTestId("notification-menu")).toBeVisible();
}

async function browserFetch(page, url, { method = "GET", body } = {}) {
  return page.evaluate(
    async ({ url: targetUrl, method: requestMethod, body: requestBody }) => {
      const response = await fetch(targetUrl, {
        method: requestMethod,
        credentials: "same-origin",
        headers: requestBody ? { "Content-Type": "application/json" } : undefined,
        body: requestBody ? JSON.stringify(requestBody) : undefined,
      });
      let payload = null;
      try {
        payload = await response.json();
      } catch {
        payload = null;
      }
      return { status: response.status, ok: response.ok, payload };
    },
    { url, method, body }
  );
}

async function getEventIdByTitle(page, title) {
  const card = getEventCard(page, title);
  await expect(card).toBeVisible();
  const href = await card.getByRole("link", { name: "View detail" }).getAttribute("href");
  const match = String(href || "").match(/\/events\/(\d+)\/view/);
  if (!match) {
    throw new Error(`Could not extract event id for ${title}`);
  }
  return Number(match[1]);
}

async function openActivityStudio(page) {
  await page.goto("/activity");
  const studioToggle = page.locator("[data-activity-toggle='studio']");
  await expect(studioToggle).toBeVisible();
  if ((await studioToggle.getAttribute("aria-expanded")) !== "true") {
    await studioToggle.click();
  }
  await expect(page.locator("[data-activity-panel='studio']")).toBeVisible();
}

async function markLocationAsValidated(page, selectors, locationValue = "District 1, Ho Chi Minh City") {
  await page.evaluate(
    ({ selectors, locationValue }) => {
      const locationInput = document.querySelector(selectors.location);
      const latitudeInput = document.querySelector(selectors.latitude);
      const longitudeInput = document.querySelector(selectors.longitude);
      if (!(locationInput instanceof HTMLInputElement) || !(latitudeInput instanceof HTMLInputElement) || !(longitudeInput instanceof HTMLInputElement)) {
        throw new Error("Location inputs are missing.");
      }
      locationInput.value = locationValue;
      locationInput.dataset.locationValidated = "true";
      latitudeInput.value = "10.77652";
      longitudeInput.value = "106.70098";
    },
    { selectors, locationValue }
  );
}

async function submitActivityRequest(page, title) {
  await openActivityStudio(page);
  await page.locator("#activity-open-request-modal").click();
  await expect(page.locator("#activity-request-modal")).toBeVisible();
  await page.locator("#activity-owned-event-title").fill(title);
  await page.locator("#activity-owned-event-category").fill("Workshop");
  await page.locator("#activity-owned-event-description").fill("Lab 2 automated request generated by Playwright.");
  await page.locator("#activity-owned-event-venue-details").fill("Level 2, Automation Hall, check-in beside the east entrance.");
  await markLocationAsValidated(page, {
    location: "#activity-owned-event-location",
    latitude: "#activity-owned-event-latitude",
    longitude: "#activity-owned-event-longitude",
  });
  await page.locator("#activity-owned-event-start-at").fill(futureLocalDatetime(20, 18, 30));
  await page.locator("#activity-owned-event-capacity").fill("20");
  await page.locator("#activity-owned-event-price").fill("25");
  await page.locator("#activity-owned-event-submit").click();
  await expect(page.locator("#activity-request-modal")).toBeHidden();
  await expect(page.locator("#activity-owned-event-list")).toContainText(title);
}

async function createRequestViaApi(page, title) {
  const response = await browserFetch(page, "/api/me/owned-events", {
    method: "POST",
    body: {
      title,
      description: "Playwright-created event request for Lab 2 review.",
      category: "Workshop",
      location: "District 1, Ho Chi Minh City",
      venue_details: "Automation Hall, level 3.",
      start_at: `${futureLocalDatetime(25, 19, 0)}:00`,
      capacity: 30,
      price: 15,
      latitude: 10.77652,
      longitude: 106.70098,
    },
  });
  expect(response.status).toBe(201);
  return response.payload;
}

test.describe("Lab2 Playwright review mapped to workbook functions", () => {
  test("AUTH: registration, invalid login validation, and successful login", async ({ page }) => {
    const email = `lab2.auth.${Date.now()}@example.com`;

    await page.goto("/");
    await page.getByRole("button", { name: "Sign up" }).click();
    await expect(page.locator("#register-panel")).toBeVisible();
    await page.locator("#register-name").fill("Lab2 Auth User");
    await page.locator("#register-date-of-birth").fill("2004-05-20");
    await page.locator("#register-street-address").fill("12 Nguyen Van Bao");
    await page.locator("#register-phone-local").fill("912345678");
    await page.locator("#register-email").fill(email);
    await page.locator("#register-password").fill("Password123!");
    await page.locator("#register-submit").click();
    await expect(page.getByTestId("auth-message")).toContainText("Registration completed");

    await page.getByTestId("login-email").fill(email);
    await page.getByTestId("login-password").fill("WrongPass123!");
    await page.getByTestId("login-submit").click();
    await expect(page.getByTestId("login-inline-error")).toContainText("Invalid email or password.");

    await page.getByTestId("login-password").fill("Password123!");
    await page.getByTestId("login-submit").click();
    await expect(page).toHaveURL(/\/dashboard$/);
    await expect(page.getByTestId("account-trigger")).toBeVisible();
  });

  test("EVDASH: dashboard lists events and opens event detail", async ({ page }) => {
    await loginAsStudent(page);
    await expect(page.getByTestId("event-grid")).toContainText("AI Career Night");

    await page.locator("#event-search").fill("AI Career Night");
    await page.locator("#event-search-submit").click();
    const card = getEventCard(page, "AI Career Night");
    await expect(card).toBeVisible();
    await card.getByRole("link", { name: "View detail" }).click();

    await expect(page).toHaveURL(/\/events\/\d+\/view$/);
    await expect(page.getByTestId("detail-title")).toContainText("AI Career Night");
    await expect(page.getByTestId("event-price")).toContainText("$");
  });

  test("RESERVE: reserve one event and cancel it from detail page", async ({ page }) => {
    await loginAsStudent(page);
    const card = getEventCard(page, "AI Career Night");
    await card.getByRole("button", { name: "Reserve now" }).click();
    await expect(page.getByTestId("dashboard-registration-modal")).toBeVisible();
    await page.locator("#dashboard-registration-quantity").fill("1");
    await page.locator("#dashboard-registration-submit").click();
    await expect(page.getByTestId("dashboard-registration-modal")).toBeHidden();

    await card.getByRole("link", { name: "View detail" }).click();
    await expect(page.getByTestId("detail-status")).toContainText("Reserved");
    await page.getByTestId("detail-cancel").click();
    await expect(page.getByTestId("detail-status")).toContainText("Not reserved yet");
  });

  test("CAPACITY: accepts quantity 5 after top-up and rejects quantity 6", async ({ page }) => {
    await loginAsStudent(page);

    const topUpResponse = await browserFetch(page, "/api/me/wallet/top-up", {
      method: "POST",
      body: { amount: 50, provider: "QR transfer", note: "Lab2 top-up for capacity validation" },
    });
    expect(topUpResponse.status).toBe(200);
    const confirmResponse = await browserFetch(page, "/api/me/wallet/top-up/confirm", { method: "POST" });
    expect(confirmResponse.status).toBe(200);

    const eventId = await getEventIdByTitle(page, "AI Career Night");
    const quantityFive = await browserFetch(page, `/api/events/${eventId}/register`, {
      method: "POST",
      body: {
        quantity: 5,
        attendee_name: "Capacity User",
        attendee_email: "student@example.com",
        attendee_phone: "+84 912345678",
      },
    });
    expect(quantityFive.status).toBe(200);
    expect(quantityFive.payload.registered_count).toBeGreaterThanOrEqual(5);

    const cancelResponse = await browserFetch(page, `/api/events/${eventId}/register`, { method: "DELETE" });
    expect(cancelResponse.status).toBe(200);

    const quantitySix = await browserFetch(page, `/api/events/${eventId}/register`, {
      method: "POST",
      body: {
        quantity: 6,
        attendee_name: "Capacity User",
        attendee_email: "student@example.com",
        attendee_phone: "+84 912345678",
      },
    });
    expect(quantitySix.status).toBe(422);
  });

  test("BILLQR: generate QR top-up, lock the form, confirm payment, and record transaction", async ({ page }) => {
    await loginAsStudent(page);
    await page.goto("/account/billing");
    const balanceBeforeText = await page.locator("#wallet-balance").textContent();
    const balanceBefore = Number(String(balanceBeforeText || "").replace(/[^0-9.-]/g, "")) || 0;

    const topupToggle = page.locator("[data-billing-toggle='topup']");
    await topupToggle.click();
    await expect(page.locator("[data-billing-panel='topup']")).toBeVisible();
    await page.locator("#wallet-topup-amount").fill("25");
    await page.locator("#wallet-topup-note").fill("Lab2 billing automation");
    await page.locator("#wallet-topup-submit").click();

    await expect(page.locator("#wallet-topup-submit")).toContainText("Generate QR again in");
    await expect(page.locator("#wallet-topup-amount")).toBeDisabled();
    await page.locator("#wallet-confirm-button").click();

    await expect.poll(async () => {
      const walletResponse = await browserFetch(page, "/api/me/wallet");
      const nextBalance = Number(walletResponse.payload?.user?.balance || 0);
      return nextBalance;
    }).toBeGreaterThan(balanceBefore);

    const transactionsToggle = page.locator("[data-billing-toggle='transactions']");
    if ((await transactionsToggle.getAttribute("aria-expanded")) !== "true") {
      await transactionsToggle.click();
    }
    await expect(page.locator("[data-billing-panel='transactions']")).toBeVisible();
    await expect(page.locator("#wallet-transaction-list")).toContainText("top up");
  });

  test("REQSUB: submit an event request and show the request notification", async ({ page }) => {
    const title = uniqueLabel("Lab2 Request");
    await loginAsStudent(page);
    const createdRequest = await createRequestViaApi(page, title);
    expect(createdRequest.approval_status).toBe("pending");

    await page.goto("/activity");
    await expect(page.locator("#activity-owned-event-list")).toContainText(title);
    await expect(page.locator("#activity-owned-event-list")).toContainText("Pending review");

    await expect(page.getByTestId("notification-badge")).toBeVisible();
    await openNotificationMenu(page);
    await expect(page.getByTestId("notification-list")).toContainText("Send Event Request");
    await expect(page.getByTestId("notification-list")).toContainText(title);
  });

  test("ADMINAPR: admin approves and rejects pending requests from the manager queue", async ({ browser }) => {
    const approveTitle = uniqueLabel("Lab2 Approve");
    const rejectTitle = uniqueLabel("Lab2 Reject");

    const studentContext = await browser.newContext();
    const studentPage = await studentContext.newPage();
    await loginAsStudent(studentPage);
    await createRequestViaApi(studentPage, approveTitle);
    await createRequestViaApi(studentPage, rejectTitle);
    await studentContext.close();

    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();
    await loginAsAdmin(adminPage);
    await adminPage.getByTestId("admin-manager-link").click();
    await expect(adminPage).toHaveURL(/\/admin\/manager$/);

    const approveItem = adminPage.locator("#admin-manager-list .admin-manager-item").filter({ hasText: approveTitle }).first();
    await expect(approveItem).toBeVisible();
    await approveItem.getByRole("button", { name: "Approve" }).click();
    await expect(adminPage.locator("#admin-manager-list .admin-manager-item").filter({ hasText: approveTitle }).first()).toContainText("Approved");

    const rejectItem = adminPage.locator("#admin-manager-list .admin-manager-item").filter({ hasText: rejectTitle }).first();
    await expect(rejectItem).toBeVisible();
    await rejectItem.getByRole("button", { name: "Reject" }).click();
    await expect(adminPage.locator("#admin-manager-list .admin-manager-item").filter({ hasText: rejectTitle }).first()).toContainText("Needs revision");
    await adminContext.close();
  });

  test("NOTIFY: student receives approval notification with event link", async ({ browser }) => {
    const title = uniqueLabel("Lab2 Notify");

    const studentContext = await browser.newContext();
    const studentPage = await studentContext.newPage();
    await loginAsStudent(studentPage);
    const createdRequest = await createRequestViaApi(studentPage, title);

    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();
    await loginAsAdmin(adminPage);
    const approveResponse = await browserFetch(adminPage, `/api/admin/events/${createdRequest.id}/approve`, { method: "POST" });
    expect(approveResponse.status).toBe(200);
    await adminContext.close();

    await studentPage.reload();
    await expect(studentPage.getByTestId("notification-badge")).toBeVisible();
    await openNotificationMenu(studentPage);
    const approvedNotification = studentPage.locator(".notification-item").filter({ hasText: title }).first();
    await expect(approvedNotification).toContainText("Event approved");
    await expect(approvedNotification).toHaveAttribute("href", new RegExp(`/events/${createdRequest.id}/view`));
    await studentContext.close();
  });
});
